-- Generated by nwg-displays on 2026-07-24 at 10:21:29. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    disabled = true
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = 1.0
})
