-- Generated by nwg-displays on 2026-07-20 at 15:19:52. Do not edit manually.

hl.monitor({
	output = "eDP-1",
	mode = "1920x1080@120.03",
	position = "1920x0",
	scale = 1.0,
})
hl.monitor({
	output = "HDMI-A-3",
	mode = "1920x1080@60.0",
	position = "0x0",
	scale = 1.0,
})
