# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# A minimal left prompt
# format = """$character"""

# move the rest of the prompt to the right
# right_format = """$all"""

[aws]
disabled = true

[direnv]
detect_files = [
  ".envrc",
  ".env",
  ".env.local",
  ".env.dev",
  ".env.development",
  ".env.test",
  ".env.prod",
  ".env.production",
]
