#!/bin/sh
xrandr --output eDP-1 --off \
	--output HDMI-1-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal
# or
xrandr --output eDP-1 --off \
	--output HDMI-1-3 --primary --mode 1920x1080 --pos 0x0 --rotate normal

nitrogen --restore
