#!/bin/bash

. "$HOME"/.dmenurc
dmenu_cmd="dmenu $DMENU_OPTIONS"
direction=$(echo -e 'left\nright' | $dmenu_cmd)

case "$direction" in
"left")
	xrandr --output eDP-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal \
		--output HDMI-1-1 --mode 1920x1080 --pos 0x0 --rotate normal
	# or
	xrandr --output eDP-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal \
		--output HDMI-1-3 --mode 1920x1080 --pos 0x0 --rotate normal
	;;
"right")
	xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal \
		--output HDMI-1-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal
	# or
	xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal \
		--output HDMI-1-3 --primary --mode 1920x1080 --pos 1920x0 --rotate normal
	;;
*) ;;
esac

nitrogen --restore

# xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off --output HDMI-2 --off --output DP-2 --off --output HDMI-3 --off --output HDMI-1-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal
