#!/bin/sh
#
xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1-1 --off
# or
xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1-3 --off
# xrandr --output DP-1 --off
# xrandr --output HDMI-2 --off
# xrandr --output DP-2 --off
# xrandr --output HDMI-3 --off
# xrandr --output HDMI-1-1 --off
# xrandr --output HDMI-1-3 --off

# sleep 1
# nitrogen --head=0 --set-zoom-fill /mnt/d/data/media/pictures/wallpapers/linux/tux/tux-mocha.png
# nitrogen --restore
feh --bg-fill "$HOME"/.local/share/wallpaper.jpg
