#!/bin/sh
xrandr --output eDP-1 --primary --mode 1920x1080 --pos 1080x840 --rotate normal --output DP-1 --off --output HDMI-1 --off --output DP-2 --off --output HDMI-2 --off --output HDMI-1-3 --mode 1920x1080 --pos 0x0 --rotate right

# nitrogen --head=0 --set-zoom-fill /mnt/d/data/media/pictures/wallpapers/linux/tux/tux-mocha.png
# nitrogen --head=1 --set-zoom-fill /mnt/d/data/media/pictures/wallpapers/linux/tux/tux-mocha.png
#
nitrogen --restore
