#!/bin/sh

xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --output HDMI-1-1 --mode 1920x1080 --pos 0x0
xrandr --output HDMI-1-1 --same-as eDP-1
xrandr --output HDMI-1-3 --mode 1920x1080 --pos 0x0
xrandr --output HDMI-1-3 --same-as eDP-1

# nitrogen --head=0 --set-zoom-fill /mnt/d/data/media/pictures/wallpapers/linux/tux/tux-mocha.png
# nitrogen --restore
